DROP DATABASE IF EXISTS `asperger`;
CREATE DATABASE `asperger` CHARACTER SET utf8;

USE `asperger`;

CREATE TABLE `Users`
(
    `id`    TINYINT         UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `name`  VARCHAR(50)     NOT NULL,
    `image` VARCHAR(50)     UNIQUE,
    `email` VARCHAR(100)    NOT NULL    UNIQUE,
    `pass`  VARCHAR(100)    NOT NULL
)
    ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `Tests`
(
    `id`          TINYINT       UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
    `category`    CHAR(2)       NOT NULL,
    `number`      TINYINT(2)    NOT NULL,
    `answer`      TINYINT(1)    NOT NULL,
    `question`    VARCHAR(120)  NOT NULL    UNIQUE
)
    ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO `Tests` (`category`, `number`, `answer`, `question`) VALUES
('AQ', 1, 0,  'Je préfère réaliser des activités avec d’autres personnes plutôt que seul(e).'),
('AQ', 2, 1,  'Je préfère tout faire continuellement de la même manière.'),
('AQ', 3, 0,  'Quand j’essaye d’imaginer quelque chose, il est très facile de m’en représenter une image mentalement.'),
('AQ', 4, 1,  'Je suis fréquemment tellement absorbé(e) par une chose que je perds tout le reste de vue.'),
('AQ', 5, 1,  'Mon attention est souvent attirée par des bruits discrets que les autres ne remarquent pas.'),
('AQ', 6, 1,  'Je fais habituellement attention aux numéros de plaques d’immatriculation ou à d’autres types d’informations de ce genre.'),
('AQ', 7, 1,  'Les gens me disent souvent que ce que j’ai dit était impoli, même quand je pense moi que c’était poli.'),
('AQ', 8, 0,  'Quand je lis une histoire, je peux facilement imaginer à quoi les personnages pourraient ressembler.'),
('AQ', 9, 1,  'Je suis fasciné(e) par les dates.'),
('AQ', 10, 0, 'Au sein d’un groupe, je peux facilement suivre les conversations de plusieurs personnes à la fois.'),
('AQ', 11, 0, 'Je trouve les situations de la vie en société faciles.'),
('AQ', 12, 1, 'J’ai tendance à remarquer certains détails que les autres ne voient pas.'),
('AQ', 13, 1, 'Je préfèrerais aller dans une bibliothèque plutôt qu’à une fête.'),
('AQ', 14, 0, 'Je trouve facile d’inventer des histoires.'),
('AQ', 15, 0, 'Je suis plus facilement attiré(e) par les gens que par les objets.'),
('AQ', 16, 1, 'J’ai tendance à avoir des centres d’intérêt très importants. Je me tracasse lorsque je ne peux m’y consacrer.'),
('AQ', 17, 0, 'J’apprécie le bavardage en société.'),
('AQ', 18, 1, 'Quand je parle, il n’est pas toujours facile pour les autres de placer un mot.'),
('AQ', 19, 1, 'Je suis fasciné(e) par les chiffres.'),
('AQ', 20, 1, 'Quand je lis une histoire, je trouve qu’il est difficile de me représenter les intentions des personnages.'),
('AQ', 21, 1, 'Je n’aime pas particulièrement lire des romans.'),
('AQ', 22, 1, 'Je trouve qu’il est difficile de se faire de nouveaux amis.'),
('AQ', 23, 1, 'Je remarque sans cesse des schémas réguliers dans les choses qui m’entourent.'),
('AQ', 24, 0, 'Je préfèrerais aller au théâtre qu’au musée.'),
('AQ', 25, 0, 'Cela ne me dérange pas si mes habitudes quotidiennes sont perturbées.'),
('AQ', 26, 1, 'Je remarque souvent que je ne sais pas comment entretenir une conversation.'),
('AQ', 27, 0, 'Je trouve qu’il est facile de « lire entre les lignes » lorsque quelqu’un me parle.'),
('AQ', 28, 0, 'Je me concentre habituellement plus sur l’ensemble d’une image que sur les petits détails de celle-ci.'),
('AQ', 29, 0, 'Je ne suis pas très doué(e) pour me souvenir des numéros de téléphone.'),
('AQ', 30, 0, 'Je ne remarque habituellement pas les petits changements dans une situation ou dans l’apparence de quelqu’un.'),
('AQ', 31, 0, 'Je sais m’en rendre compte quand mon interlocuteur s’ennuie.'),
('AQ', 32, 0, 'Je trouve qu’il est facile de faire plus d’une chose à la fois.'),
('AQ', 33, 1, 'Quand je parle au téléphone, je ne suis pas sûr(e) de savoir quand c’est à mon tour de parler.'),
('AQ', 34, 0, 'J’aime faire les choses de manière spontanée.'),
('AQ', 35, 1, 'Je suis souvent le(la) dernier(ère) à comprendre le sens d’une blague.'),
('AQ', 36, 0, 'Je trouve qu’il est facile de décoder ce que les autres pensent ou ressentent juste en regardant leur visage.'),
('AQ', 37, 0, 'Si je suis interrompu(e), je peux facilement revenir à ce que j’étais en train de faire.'),
('AQ', 38, 0, 'Je suis doué(e) pour le bavardage en société.'),
('AQ', 39, 1, 'Les gens me disent souvent que répète continuellement les mêmes choses.'),
('AQ', 40, 0, 'Quand j’étais enfant, j’aimais habituellement jouer à des jeux de rôle avec les autres.'),
('AQ', 41, 1, 'J’aime collectionner des informations sur des catégories de choses (types de voitures, d’oiseaux, de trains, de plantes, ...).'),
('AQ', 42, 1, 'Je trouve qu’il est difficile de s’imaginer dans la peau d’un autre.'),
('AQ', 43, 1, 'J’aime planifier avec soin toute activité à laquelle je participe.'),
('AQ', 44, 0, 'J’aime les événements sociaux.'),
('AQ', 45, 1, 'Je trouve qu’il est difficile de décoder les intentions des autres.'),
('AQ', 46, 1, 'Les nouvelles situations me rendent anxieux(se).'),
('AQ', 47, 0, 'J’aime rencontrer de nouvelles personnes.'),
('AQ', 48, 0, 'Je suis une personne qui a le sens de la diplomatie.'),
('AQ', 49, 0, 'Je ne suis pas très doué(e) pour me souvenir des dates de naissance des gens.'),
('AQ', 50, 0, 'Je trouve qu’il est très facile de jouer à des jeux de rôle avec des enfants.'),
('EQ', 1, 1, 'I can easily tell if someone else wants to enter a conversation.'),
('EQ', 2, 0, 'I find it difficult to explain to others things that I understand easily, when they do not understand it first time.'),
('EQ', 3, 1, 'I really enjoy caring for other people.'),
('EQ', 4, 0, 'I find it hard to know what to do in a social situation.'),
('EQ', 5, 0, 'People often tell me that I went too far in driving my point home in a discussion.'),
('EQ', 6, 0, 'It does not bother me too much if I am late meeting a friend.'),
('EQ', 7, 0, 'Friendships and relationships are just too difficult, strongly slightly so I tend not to bother with them.'),
('EQ', 8, 0, 'I often find it difficult to judge if something is rude strongly slightly or polite.'),
('EQ', 9, 0, 'In a conversation, I tend to focus on my own thoughts rather than on what my listener might be agree thinking.'),
('EQ', 10, 0, 'When I was a child, I enjoyed cutting up worms to strongly slightly see what would happen.'),
('EQ', 11, 1, 'I can pick up quickly if someone says one thing but strongly slightly means another.'),
('EQ', 12, 0, 'It is hard for me to see why some things upset people so much.'),
('EQ', 13, 1, 'I find it easy to put myself in somebody else’s shoes.'),
('EQ', 14, 1, 'I am good at predicting how someone will feel.'),
('EQ', 15, 1, 'I am quick to spot when someone in a group is feeling awkward or uncomfortable.'),
('EQ', 16, 0, 'If I say something that someone else is offended by, I think that that is their problem, not mine.'),
('EQ', 17, 0, 'If anyone asked me if I liked their haircut, I would strongly slightly reply truthfully, even if I did not like it.'),
('EQ', 18, 0, 'I cannot always see why someone should have felt offended by a remark.'),
('EQ', 19, 0, 'Seeing people cry does not really upset me.'),
('EQ', 20, 0, 'I am very blunt, which some people take to be rudeness, even though this is unintentional.'),
('EQ', 21, 1, 'I don’t tend to find social situations confusing.'),
('EQ', 22, 1, 'Other people tell me I am good at understanding how they are feeling and what they are thinking.'),
('EQ', 23, 1, 'When I talk to people, I tend to talk about their experiences rather than my own.'),
('EQ', 24, 1, 'It upsets me to see an animal in pain.'),
('EQ', 25, 0, 'I am able to make decisions without being influenced by people’s feelings.'),
('EQ', 26, 1, 'I can easily tell if someone else is interested or bored with what I am saying.'),
('EQ', 27, 1, 'I get upset if I see people suffering on news programmes.'),
('EQ', 28, 1, 'Friends usually talk to me about their problems as strongly slightly they say that I am very understanding.'),
('EQ', 29, 1, 'I can sense if I am intruding, even if the other person does not tell me.'),
('EQ', 30, 0, 'People sometimes tell me that I have gone too far with teasing.'),
('EQ', 31, 0, 'Other people often say that I am insensitive, though I don’t always see why.'),
('EQ', 32, 0, 'If I see a stranger in a group, I think that it is up to strongly slightly them to make an effort to join in.'),
('EQ', 33, 0, 'I usually stay emotionally detached when watching strongly slightly a film.'),
('EQ', 34, 1, 'I can tune into how someone else feels rapidly and strongly slightly intuitively.'),
('EQ', 35, 1, 'I can easily work out what another person might want to talk about.'),
('EQ', 36, 1, 'I can tell if someone is masking their true emotion.'),
('EQ', 37, 1, 'I do not consciously work out the rules of social situations.'),
('EQ', 38, 1, 'I am good at predicting what someone will do.'),
('EQ', 39, 1, 'I tend to get emotionally involved with a friend’s problems.'),
('EQ', 40, 1, 'I can usually appreciate the other person’s viewpoint, even if I don''t agree with it.');
